name: container
description: Run commands inside a Docker container
inputs:
  docker_image:
    description: 'Docker image to use for the container'
    required: true
    default: 'mkmdockerhub/gha-aws:latest'

  environment:
    description: 'Environment name (e.g., dev, int, prod)'
    required: true
    default: 'dev'

runs:
  using: 'composite'
  steps:
  
    - name: Run commands inside the container
      shell: bash
      run: |
        echo "Starting the container..."
        CONTAINER_ID=$(docker run -d \
          -v ${{ github.workspace }}:/workspace \
          -v ~/.aws:/root/.aws \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION \
          -w /workspace \
          ${{ inputs.docker_image }} \
          tail -f /dev/null)
        echo "CONTAINER_ID=$CONTAINER_ID" >> "$GITHUB_ENV"

    - name: print contents of ~/.aws/credentials inside the container
      shell: bash
      run: |
        echo "Contents of ~/.aws/credentials inside the container:"
        docker exec "$CONTAINER_ID" cat /root/.aws/credentials

    - name: exec commands inside the running container
      shell: bash
      run: |
        docker exec "$CONTAINER_ID" bash -c "aws --version && aws sts get-caller-identity && aws s3 ls s3://mkm-gha-aws-test-bucket/ && df -hT && ls -la"
      