name: AWS OIDC EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390844777938:role/gha-role
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Get EC2 Instance IDs
        run: |
          echo "Fetching EC2 instance IDs..."
          aws ec2 describe-instances \
            --region ap-south-1 \
            --filters "Name=tag:Name,Values=mkm-instance" \
            --output text