name: AWS OIDC EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (e.g., dev, int, prod)'
        type: choice
        options:
          - dev
          - int
          - prod
        required: true
        default: dev

permissions:
  id-token: write
  contents: read

env:
  DOCKER_IMAGE: mkmdockerhub/gha-aws:latest

jobs:
  aws-oidc-ec2:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment || 'dev' }}

    #container:
    #  image: mkmdockerhub/gha-aws:latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          pwd
          ls -la
          find . -name "requirements.txt"

      - name: Check Python
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390844777938:role/gha-role
          aws-region: ap-south-1

      - name: Multiple AWS profiles
        run: |
          mkdir -p "$HOME/.aws"
          for profile in "$ENVIRONMENT"; do
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile "$profile"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile "$profile"
            aws configure set aws_session_token "$AWS_SESSION_TOKEN" --profile "$profile"
            aws configure set region ap-south-1 --profile "$profile"
          done

      - name: print AWS profiles on host and its contents
        run: |
          echo "Configured AWS profiles:"
          aws configure list --profile "$ENVIRONMENT"
          echo "Contents of ~/.aws/credentials:"
          cat ~/.aws/credentials

      - name: Get EC2 Instance IDs on host
        run: |
            echo "=== AWS Identity ==="
            aws sts get-caller-identity --profile "$ENVIRONMENT"

            echo "=== EC2 Instances in ap-south-1 ==="
            aws ec2 describe-instances \
            --region ap-south-1 \
            --query "Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key=='Name']|[0].Value]" \
            --output text
      
      - name: Upload file to S3 on host
        run: |
          echo "Uploading file to S3 bucket..."
          aws s3 cp ./README.md s3://mkm-gha-aws-test-bucket/README.md
          echo "File uploaded successfully."

      - name: List files in S3 bucket on host
        run: |
          echo "Listing files in S3 bucket..."
          aws s3 ls s3://mkm-gha-aws-test-bucket/

      - name: Run aws inside container
        id: run-aws-inside-container
        uses: mkmadhul2026/gha-aws/container@main
        with:
          docker_image: ${{ env.DOCKER_IMAGE }}